### ISSUE TITLE
As a Meeting Room manager I want the ePaper Meeting Room display manager app online, to use it for my meeting rooms.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/epaper-meetingroom-display-server#2]
Agreed deadline: end of April

**Comment by RudiThoeni** [comment]
@sseppi Deployed on [](https://meetingroominfo.testingmachine.eu/)
with the route /jobs a Dashboard is opened (will provide you the access)
other i tested is passing label_id in the header like `B0:B2:1C:60:BD:E0`
and going to [](https://meetingroominfo.testingmachine.eu/api/room) seems to work....

**Comment by RudiThoeni** [comment]
waiting for a datetime bug to be resolved before deploying it to produciton

**Comment by RudiThoeni** [comment]
to check if the datetime bug has been solved

**Comment by RudiThoeni** [comment]
@sseppi i noticed that there are some commits about a datetime bug already on the repo (https://github.com/noi-techpark/epaper-meetingroom-display-server/commit/f394445dcafe9e0e23081ca162886a81445b20c3) so this commit did not resolved the issue? still waiting for the PR here

**Comment by sseppi** [comment]
@RudiThoeni I'll check with the developer and let you know
